# Site settings
title: PaulVerrinder
author: Paul Verrinder
description: >-
  My personal website.
url: "https://paulverrinder.com"

collections:
  projects:
    output: true
  writing:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Excluded from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - 0_drafts
